name: Browserstack
on: [push]

jobs:
  browserstack:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        target-browser: [chrome_windows, edge_windows, firefox_windows, safari_11_mac, ios_14, android_11]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js 12
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - name: 'Browserstack Env Setup'
      uses: 'browserstack/github-actions/setup-env@master'
      with:
        username: ${{ secrets.BROWSERSTACK_USERNAME }}
        access-key: ${{ secrets.BROWSERSTACK_ACCESS_KEY }}
    - name: run Browserstack tests - ${{ matrix.target-browser }}
      run: |
        npm install
        npm run test:browser_remote
      env:
        CI: true
        TARGET_BROWSER: ${{ matrix.target-browser }}
