name: Browserstack
on: [push]

jobs:
  browserstack:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js 12
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - name: 'Browserstack Env Setup'
      uses: 'browserstack/github-actions/setup-env@master'
      with:
        username: ${{ secrets.BROWSERSTACK_USERNAME }}
        access-key: ${{ secrets.BROWSERSTACK_ACCESS_KEY }}
    - name: run Browserstack tests
      run: |
        npm install
        npm run test:browser_remote
      env:
        CI: true
